server:
  port: 8080

spring:
  application:
    name: smallestShelter

  datasource:
    platform: mysql
    url:  jdbc:mysql://umcdb.c8xezlmvz99n.ap-northeast-2.rds.amazonaws.com:3306/umcSJS
    username: umc
    password: chamsaenunjack55
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전